name: Social Lunch - Pedido Mensual

on:
  # Ejecutar el día 1 de cada mes a las 9:00 AM (hora Argentina = 12:00 UTC)
  schedule:
    - cron: '0 12 1 * *'
  
  # También permitir ejecución manual desde GitHub
  workflow_dispatch:

jobs:
  hacer-pedido:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
      
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Instalar dependencias
        run: |
          pip install playwright
          playwright install chromium
          playwright install-deps
      
      - name: Ejecutar bot
        env:
          SOCIALLUNCH_USER: ${{ secrets.SOCIALLUNCH_USER }}
          SOCIALLUNCH_PASS: ${{ secrets.SOCIALLUNCH_PASS }}
        run: python sociallunch_bot.py
      
      - name: Notificar resultado
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "✅ Pedido mensual completado exitosamente"
          else
            echo "❌ Hubo un error en el pedido"
          fi
